# Generated by Django 5.2.13 on 2026-04-26 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=50)),
                ('row', models.CharField(max_length=10)),
                ('seat_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_venue', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HasRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=50)),
                ('seat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.seat')),
            ],
        ),
        migrations.AddField(
            model_name='seat',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.venue'),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('venue', 'section', 'row', 'seat_number')},
        ),
    ]
