# Generated by Django 6.0.4 on 2026-04-30 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_artist_event_eventartist_order_orderpromotion_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hasrelationship',
            table='has_relationship',
        ),
        migrations.AlterModelTable(
            name='seat',
            table='seat',
        ),
        migrations.AlterModelTable(
            name='venue',
            table='venue',
        ),
    ]
